# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fb6eebd12685acb5f82a84f20b2ceaa975b7b511f840d1ff5910609cd01b256f22cdd7131ca384185cf39efa92979b1dc8e0e179c3d84132608894f3f66339

test:
  secret_key_base: 19e8edde14e9be21d206e5f6a29da4002beb3790f7425ea1e89d8d3f1a5fcaa8ba7ee10611debbecc280b7ca0bda10ea231c54d4a908c26ff842a6294534609b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
